<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net9.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Bullseye_Calculator\Bullseye_Calculator.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Update="Icon\icon.ico">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
	<Page Update="Resources\ListViewStyle.xaml">
	  <SubType>Designer</SubType>
	</Page>
	<Page Update="Resources\ExpanderStyle.xaml">
	  <SubType>Designer</SubType>
	</Page>
	<Page Update="Resources\LabelStyle.xaml">
	  <SubType>Designer</SubType>
	</Page>
  </ItemGroup>

</Project>
